### ISSUE TITLE
Can devs create new Farcaster accounts via SDK?

### ISSUE THREAD

**Issue by jfornear** [a16z/farcaster-py#211]
```
# To use the Farcaster API you need to have a Farcaster account. 
# Next, save your Farcaster mnemonic or private key to a .env file.
# Now you can initialize the client, and automatically connect to the Farcaster API!

import os
from farcaster import MerkleApiClient
from dotenv import load_dotenv

load_dotenv()

client = MerkleApiClient(mnemonic=os.environ.get("<MNEMONIC_ENV_VAR>"))

print(client.get_healthcheck())
```

Compare to [Nostr](https://github.com/jeffthibault/python-nostr) which allows generating new keys:

```
from nostr.key import PrivateKey

private_key = PrivateKey()
public_key = private_key.public_key
print(f"Private key: {private_key.bech32()}")
print(f"Public key: {public_key.bech32()}")
```

**Comment by emlazzarin** [comment]
Farcaster is limiting sign-ups as the protocol and clients are developed. Eventually, the sign-up process will be similar to what you've described there. The Farcaster namespa﻿ce (`fid`s) will be on Ethereum mainnet or similar.

The protocol specification page, linked [here](https://github.com/farcasterxyz/protocol#21-farcaster-ids), outlines how developers are thinking about it so far. Permissionlessness is a clear design goal. Some more documentation links [here](https://github.com/a16z/awesome-farcaster#documentation).
