### ISSUE TITLE
Cursor not included in response for iterable endpoints

### ISSUE THREAD

**Issue by payton** [a16z/farcaster-py#251]
## 🐛 Bug Report

When making a call to most endpoints exposed by farcaster-py, there is an option of including a cursor to continue an existing iteration. However, the response of these endpoints does NOT include the cursor returned by Merkle. This makes it impossible (to do in a reasonable way) to iterate over results.

For example, a call to `get_recent_casts(...)` returns a `CastsResult` object that is derived from `CastsGetResponse`. However, we should also be including the cursor in `CastsGetResponse`.

https://github.com/a16z/farcaster-py/blob/3f5f1d855f0f7d2c5f6222b73267230b79667e3b/farcaster/models.py#L505-L507
https://github.com/a16z/farcaster-py/blob/98964e05750202ba8529c4d26dd12f42134f93ed/farcaster/client.py#L822-L840

## 📈 Expected behavior

A call to `get_recent_casts(...)` (and other iterable endpoints) should also return a cursor associated with that iteration.

**Comment by dakshas** [comment]
Ran into this too. Any idea what it will take to get your changes reviewed and merged ?

**Comment by payton** [comment]
cc: @fmhall

**Comment by fmhall** [comment]
@dakshas This has been fixed
