### ISSUE TITLE
Can't import anything from farcaster

### ISSUE THREAD

**Issue by sanchitram1** [a16z/farcaster-py#357]
## 🐛 Bug Report

Don't think `farcaster` isn't initializing correctly, since I get the circular import error when trying to import anything from it.

## 🔬 How To Reproduce
```sh
$ pip install -U farcaster
$ pip install eth-account python-dotenv # 
```

```python
import time
import os

from farcaster import MerkleApiClient
from eth_account.account import Account
from dotenv import load_dotenv

load_dotenv()
Account.enable_unaudited_hdwallet_features()
ETH_ACCOUNT_SIGNER = Account.from_mnemonic(os.environ.get("<MNEMONIC_ENV_VAR>"))
```
Errors out at `from farcaster import MerkleApiClient`

### Environment

* OS: macOS
* Python version: 3.9.16

## 📈 Expected behavior

Run the first example listed in the read me here.

**Comment by sagar-a16z** [comment]
Hi Sanchit! 

```
from farcaster import MerkleApiClient
```

should be 

```
from farcaster import Warpcast
```

Let me know if that helps or if you have any more questions.

**Comment by sanchitram1** [comment]
Got it -- this was an idiotic error on my part, I named the file farcaster.py 🤦🏾
