### ISSUE TITLE
Two arguments are being passed to `logging.debug` in stream_generator.py

### ISSUE THREAD

**Issue by seanbhart** [a16z/farcaster-py#427]
Two arguments are being passed to `logging.debug` [here](https://github.com/a16z/farcaster-py/blob/6e7f5592ed4dc93b98a362dcde51391b4c3a4a6c/farcaster/utils/stream_generator.py#LL60C48-L60C48) and filling debug logs with errors.

Suggested options:
`logging.debug(f"Limit: {dynamic_limit}")`
`logging.debug("Limit: %s", dynamic_limit)`

**Comment by fmhall** [comment]
Fixed in #520 !
