### ISSUE TITLE
How do you post an image with the post_cast method?

### ISSUE THREAD

**Issue by teleyinex** [a16z/farcaster-py#446]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/a16z/farcaster-py/issues?q=is%3Aissue).

## ❓ Question

How can I post an image?

The documentation shows to pass an Embed, but it is not shown if it should be an HTTP link (which I have tried) or an URI to a local file (which I have tried).

**Comment by fmhall** [comment]
It should be an imgur link!

**Comment by fmhall** [comment]
Please let me know if you still are having trouble. Sorry for the delay. Also, feel free to join us in our telegram group!
