### ISSUE TITLE
get_cast(hash) Not working 

### ISSUE THREAD

**Issue by rahulrock213** [a16z/farcaster-py#743]
Traceback (most recent call last):
  File "/root/wrap/wrap.py", line 22, in <module>
    print(client.get_cast("0x321712dc8eccc5d2be38e38c1ef0c8916c49949a80ffe20ec5752bb23ea4d86f"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wrap/myenv/lib/python3.12/site-packages/farcaster/client.py", line 338, in get_cast
    response = self._get(
               ^^^^^^^^^^
  File "/root/wrap/myenv/lib/python3.12/site-packages/farcaster/client.py", line 89, in _get
    raise Exception(response["errors"])  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: [{'message': 'Path /v2/cast?hash=0x321712dc8eccc5d2be38e38c1ef0c8916c49949a80ffe20ec5752bb23ea4d86f does not exist'}]

```
`
import os
from farcaster import Warpcast
from dotenv import load_dotenv
from typing import List, Optional

# Load environment variables from .env file
load_dotenv()

# Get mnemonic from environment variable
mnemonic = os.getenv("FARCASTER_MNEMONIC")

# Initialize the Warpcast client
client = Warpcast(mnemonic=mnemonic)

# Check API health (optional)
print(client.get_healthcheck())
print(client.get_casts(535436, cursor=None, limit=1))
# Fetch user by username
#user = client.get_user_by_username("kannada")
#print(user.username)
#print(user.fid)
print(client.get_cast("0x321712dc8eccc5d2be38e38c1ef0c8916c49949a80ffe20ec5752bb23ea4d86f"))`
#response = client.get_cast("0x321712dc8eccc5d2be38e38c1ef0c8916c49949a80ffe20ec5752bb23ea4d86f")
#print(response.cast.author.username)
`
```

**Comment by mr-spaghetti-code** [comment]
Same issue here. What's going on?

**Comment by rahulrock213** [comment]
> Same issue here. What's going on?

i thing it solved
